//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digitalwaretest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int clienteId { get; set; }
        public string numeroIdentificaionCliente { get; set; }
        public string primerNombreCliente { get; set; }
        public string primerApellidoCliente { get; set; }
        public string segundoNombreCliente { get; set; }
        public string segundoApellidoCliente { get; set; }
        public string tipoIdentificacionCliente { get; set; }
        public string direccionCliente { get; set; }
        public string correoCliente { get; set; }
        public string telefonofijoCliente { get; set; }
        public string telefonocelCliente { get; set; }
        public System.DateTime fechaNacimientoCliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
