//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digitalwaretest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA()
        {
            this.FACTURA_PRODUCTO = new HashSet<FACTURA_PRODUCTO>();
        }
    
        public int facturaId { get; set; }
        public double totalFactura { get; set; }
        public double subtotalFactura { get; set; }
        public double IVAFactura { get; set; }
        public System.DateTime fechaFactura { get; set; }
        public Nullable<int> sedeId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual SEDE SEDE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA_PRODUCTO> FACTURA_PRODUCTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
