//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digitalwaretest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_PRODUCTO
    {
        public int facturaId { get; set; }
        public int productoId { get; set; }
        public int cantidadFactura { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
